#!/bin/bash
# Auteur : DIBREY JONATAN
# Version : 0.1
# Date de demarrage : 25/02/2026 
# No IA used

# utilisation des fonctions pour rendre le travail plus comprehensible 
# Une fonction pour la generation de Makefile
# Une fonction pour la generation du repertoire en C 
# Une fonction pour la generation du repertoire en C++
function Makefile_gen {
   touch "$1"/Makefile 

}

function C_Repo_gen {
     mkdir "$1"
     touch "$1"/test.c "$1"/test.h
     # fichier test.c
     echo "#include \"test.h\"" >> "$1"/test.c
     echo "" >> "$1"/test.c
     echo "int main(int argc, char **argv){ printf(\"hello world\n\"); return 0 ; } " >> "$1"/test.c
     # fichier test.h
     echo "#pragma once" >> "$1"/test.h
     echo "#include <stdio.h>" >> "$1"/test.h
}

function CPP_Repo_gen {
    mkdir "$1"
    touch "$1"/test.cpp "$1"/test.h 
    # fichier test.cpp
    echo "#include \"test.h\"" >> "$1"/test.cpp
    echo "" >> "$1"/test.cpp
    echo "int main(int argc, char ** argv) { std::cout << \"hello world\" <<std::endl ; return 0 ; } " >> "$1"/test.cpp
    # fichier test.h
    echo "#pragma once" >> "$1"/test.h
    echo "#include <iostream>" >> "$1"/test.h
    

}

echo " L'Outil genesis est conçu pour générer automatiquement des templates pour projet C ou C++"

# Definit le nom du projet 
PROJECT_NAME=""
# Pour choisir le language de programmation 
LANGUAGE=""
# J'ai ajouté ce bloque de code car quand on oublie de passer un arguement le program tourne en une boucle infinie.
# Le but de ce code est de lire les arguements si la taille de $# est 4, si non on cherche à savoir si l'utilisateur veut juste faire une recherche -h ou --help
# Si non on déclanche une erreur, et on sort
if [ "$#" -lt 4 ] ; then 
  if [ "$1" == "-h" -o "$1" == "--help" ] ; then 
  echo -e "" 
   
   else 
   echo " essayez la commande : genesis --help pour avoir plus d'information "
   exit 1 

   fi 
else 
  echo -e ""
  fi 

# Ici je cherche à lire les arguements passé 
# Quand il n'y a pas d'arguement $# c'est 0 
# Donc à chaque fois on lit $1 et $2 et on decale à gauche de 2, jusquà arriver à $#=0  
while [[ "$#" -gt 0 ]] ; do 
    case "$1" in 
    --cxx | -l )
    LANGUAGE="$2"
    shift 2 ;; 
    --title | -t )
    PROJECT_NAME="$2"
    shift 2 ;;
    --help | -h )
    echo "Pour utiliser ce script, il faut fournir obligatoirement un nom et le language de programmation"
    echo " exemple : genesis -l c -t test  ou encore genesis --cxx cpp --title test"
    shift 2 
    exit 0 ;;  
    esac
done 

if [ -n "$PROJECT_NAME"  ] ; then 

if [ "$LANGUAGE" == "c" ] ; then 
 echo "creation d'un template en language c "
      C_Repo_gen "$PROJECT_NAME"
elif [ "$LANGUAGE" == "cpp" ] ; then 
 echo "creation d'un template en language c++ "
      CPP_Repo_gen "$PROJECT_NAME"
else 
echo " tapez genesis -h pour plus d'info "
exit 1
fi 

else 
 echo "erreur pas de nom de projet"
 echo "tapez genesis -h pour plus d'info"
 exit 1 
fi  
